Meta 20 shacl datamodel organisaties
viaacode/datamodels pull request #3
Opened 2022-03-30 07:16 UTC by milvala

2022-03-30 15:06 UTC, mielvds requested changes

2022-03-30 15:06 UTC, mielvds commented on organizations/organizations.shacl.ttl
> +                # vraag: in de data komen nu sites voor met meerdere postadressen; is dit iets dat we willen, of zetten we hier een maximum op?
Ja, volgens OSLO applicatieprofiel mag een vestiging maar 1 adres hebben. Dus eigenlijk moeten al die addressen een eigen vestiging hebben.

2022-04-11 13:09 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +<>  dct:author  [
Check.

2022-04-11 13:37 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:GovernmentOrganization   a   rdfs:Class ;
Nav. de samenwerkingsovereenkomst, dacht ik ook richting de beheersovereenkomst. In die context lijkt me de term 'overheidsorganisatie' misschien nuttig. Wat denk jij?

Daarnaast: is het de bedoeling dat alles rond juridische dingen zoals overeenkomsten in een apart datamodel komen, of hoe zie je dat?

2022-04-11 13:39 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:LogoContext  a   rdfs:Class ;
Hadden we daar niet eens over gesproken een tweetal weken geleden? Is het definiëren als een klasse geen extra manier om via de SHACL af te kunnen dwingen dat contexten tot die specifieke klasse moeten behoren? 

Als je gewoon zegt dat het een skos:Concept is, dan is het toch moeilijker om af te dwingen dat enkel bepaalde termen uit een specifiek vocabularium toegelaten worden? 

(als het duidelijk is wat ik wil zeggen)

2022-04-11 13:40 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:ManagementAgreement  a   rdfs:Class ;
Aha, dit is dus hierboven ook mijn vraag: hoe wordt het juridische aspect nu opgevat?

2022-04-11 13:41 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:OrganizationType a   rdfs:Class ;
Kan je simpel uitleggen waarom het in zo'n geval wenselijker is dan bij bv. de context van een logo? Waarom is het in het ene geval wel verkieslijk om het als een echte klasse te nemen, en in de andere beter om het gewoon als skos:Concept te zien?

2022-04-11 13:47 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +    schema:domainIncludes schema:HealthInsurancePlan,
Dit komt uit de Turtle download van schema.org zelf: https://schema.org/version/latest/schemaorg-current-https.ttl

Daarin heb je schema:contactPoints en schema:contactPoint. Die eerste is verouderd en vervangen door de tweede (met deze definitie).

Niet goed? Ik weet wel dat een HealthInsurancePlan op dit moment niet echt plek heeft bij ons, maar ik heb externe definities gewoon zo letterlijk mogelijk overgenomen.

2022-04-11 13:51 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:contains a   rdf:Property ;
Een micro juridisch modelletje dan?

2022-04-11 13:51 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:isPartOf a   rdf:Property ;
Is zo'n generisch 'maakt deel uit van' dan oke om zo'n specifieke context (figuurlijk deel uitmaken van iets als een contract) te dekken?

2022-04-11 13:52 UTC, milvala commented on organizations/organizations.rdfs.ttl
> +meemoo:hasContactPoint  a   rdf:Property ;
Ik pas het aan!

2022-04-14 11:59 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +meemoo:LogoContext  a   rdfs:Class ;
Het is duidelijk; ik denk gewoon dat we niet alles moeten afdwingen, bij sommige zaken steekt het niet zo nauw en je maakt het model complexer (alweer een klasse om te definiëren). Mss moeten we de hele logo context voorlopig zelf skippen, want je kan ook altijd een `rdf:type` gebruiken om duidelijk te maken wat voor logo het is (en die kunnen dan ook weer uit een thesaurus komen, etc etc).

2022-04-14 12:01 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +meemoo:ManagementAgreement  a   rdfs:Class ;
de crux is dat we het in dit model helemaal niet over het juridische aspect (willen) hebben.

2022-04-14 12:05 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +meemoo:OrganizationType a   rdfs:Class ;
Omdat we hier effectief een taxonomy hebben; er is eindige en gekende [lijst](https://meemoo.atlassian.net/wiki/spaces/IK/pages/3408789605/2022+V2+-+Glossary+-+Bedrijven+en+contacten#Bedrijf%3A-1.1---Type-organisatie). Bij logo's is de use case nog te vaag

2022-04-14 12:11 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +meemoo:contains a   rdf:Property ;
jup. Maar ik zou dit niet prioritair noemen

2022-04-14 12:33 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +meemoo:isPartOf a   rdf:Property ;
ja, want de nodige nuance zit dan het het type van het ding waar het deel van uitmaakt, namelijk een contract.

2022-04-14 12:35 UTC, mielvds commented on organizations/organizations.rdfs.ttl
> +    schema:domainIncludes schema:HealthInsurancePlan,
ja ik snap het, maar het gaat hier over een schema.org construct dat wij niet per se moeten herhalen (moest het nu `rdfs:domain` zijn, dan wel.) Mensen die de schema.org definities willen gebruiken moeten dan maar de file naarwaar je verwees erbij nemen.

2022-06-27 14:41 UTC, merged